language: node_js
node_js:
- stable
env:
  global:
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0
git:
  depth: 1
addons:
  chrome: stable
  ssh_known_hosts: staging.bookabook.tk
cache:
  directories:
  - web/node_modules
before_install:
- bash _scripts/install.sh
before_script:
- npm install -g @angular/cli
script:
- cd web
- npm config set loglevel warn
- npm install
- ng test --watch=false
after_success:
- bash _scripts/deploy.sh
