language: node_js
node_js:
  - stable 

env:
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0
git:
  depth: 1
addons:
  chrome: stable
cache:
  directories:
    - web/node_modules

before_script:
  - npm install -g @angular/cli

script:
  - cd web
  - npm config set loglevel warn
  - npm install
  - ng test