language: node_js
node_js:
- stable
env:
  global:
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0
git:
  depth: 1
addons:
  chrome: stable
  ssh_known_hosts: staging.bookabook.tk
cache:
  directories:
  - web/node_modules
before_script:
- npm install -g @angular/cli
- bash _scripts/install.sh
script:
- cd web
- npm config set loglevel warn
- npm install
- ng test --watch=false
before_install:
- openssl aes-256-cbc -K $encrypted_a6f7567b205a_key -iv $encrypted_a6f7567b205a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
