language: node_js
node_js:
- stable
env:
  global:
  - CHROME_BIN=/usr/bin/google-chrome
  - DISPLAY=:99.0
git:
  depth: 1
addons:
  chrome: stable
  ssh_known_hosts: stage.bookabook.tk
cache:
  directories:
  - web/node_modules
branches:
  only: development
before_install:
- bash _scripts/install.sh
before_script:
- npm install -g @angular/cli
script:
- cd api
- npm install
- npm start &
- sleep 2
- cd ../web
- npm config set loglevel warn
- npm cache clear --force
- npm install
- ng test --watch=false
after_success:
- ng build --configuration=prod
- cd ..
- bash _scripts/deploy.sh
