#!/bin/bash

NOW=$(date +"D%y%m%dT%T" | tr -d ":")


cd /var/www/bookabook.tk/

tar -czf .web.bak/$NOW.tar.gz web
rm web/* -rf
scp -r stage-server:/var/www/bookabook.tk/web/* web/

tar -czf .api.bak/$NOW.tar.gz api
cd api
pm2 stop --silent index
rm * -rf
scp -r stage-server:/var/www/bookabook.tk/api/* .
npm install
pm2 start --interpreter babel-node index.js
